// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOnfB1OMZBMv9oRA34ilflfa_dhFiDO9w',
    appId: '1:891260879562:web:94e7f268614484ae14aa33',
    messagingSenderId: '891260879562',
    projectId: 'ditonton-a36c6',
    authDomain: 'ditonton-a36c6.firebaseapp.com',
    storageBucket: 'ditonton-a36c6.firebasestorage.app',
    measurementId: 'G-HFRL6HWLP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFuLWe3szvGNS32Zvy77Ghv0jqfSfljrA',
    appId: '1:891260879562:android:256de2930c248d4a14aa33',
    messagingSenderId: '891260879562',
    projectId: 'ditonton-a36c6',
    storageBucket: 'ditonton-a36c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdJ78y-T4eAiOGkgPKSacHBzheYsUFpCk',
    appId: '1:891260879562:ios:d27346d72d4be13e14aa33',
    messagingSenderId: '891260879562',
    projectId: 'ditonton-a36c6',
    storageBucket: 'ditonton-a36c6.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );

}